[package]
name = "dex-checker"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.1", features = ["full"] }
serde = "1.0.217"
serde_json = "1.0"
reqwest = { version = "0.11.27", features = ["json", "socks", "native-tls"] }
